name: 'Generate koro-i18n Metadata'
description: 'Generate .koro-i18n/koro-i18n.repo.generated.json metadata file for using GitHub repo as realtime translation source'
author: 'Koro i18n'

branding:
  icon: 'file-text'
  color: 'purple'

inputs:
  config-path:
    description: 'Path to .koro-i18n.repo.config.toml configuration file'
    required: false
    default: '.koro-i18n.repo.config.toml'
  commit-changes:
    description: 'Whether to commit and push the generated metadata file'
    required: false
    default: 'true'
  commit-message:
    description: 'Commit message for metadata updates'
    required: false
    default: 'chore: Update koro-i18n metadata [skip ci]'

outputs:
  metadata-path:
    description: 'Path to the generated metadata file'
    value: ${{ steps.generate.outputs.metadata-path }}
  files-count:
    description: 'Number of translation files included in metadata'
    value: ${{ steps.generate.outputs.files-count }}

runs:
  using: 'composite'
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false

    - name: Check for config file
      id: check-config
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
      run: |
        if [ -f "$CONFIG_PATH" ]; then
          echo "config_exists=true" >> $GITHUB_OUTPUT
          echo "✓ Found $CONFIG_PATH"
        else
          echo "config_exists=false" >> $GITHUB_OUTPUT
          echo "::error::Configuration file not found: $CONFIG_PATH"
          exit 1
        fi

    - name: Install koro-i18n client
      id: install-client
      if: steps.check-config.outputs.config_exists == 'true'
      shell: bash
      env:
        # Use action path to locate the client library within the same repository
        ACTION_PATH: ${{ github.action_path }}
      run: |
        # Navigate from action path to client-library (action is at .github/actions/generate-metadata)
        CLIENT_LIB_PATH="$ACTION_PATH/../../../client-library"
        
        if [ ! -d "$CLIENT_LIB_PATH" ]; then
          echo "::error::Client library not found at $CLIENT_LIB_PATH"
          exit 1
        fi
        
        cd "$CLIENT_LIB_PATH"
        gem build koro_i18n.gemspec
        gem install ./koro_i18n-*.gem
        
        echo "✓ koro-i18n client installed"

    - name: Generate metadata
      id: generate
      if: steps.check-config.outputs.config_exists == 'true'
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        # Run the koro-i18n client to generate metadata
        koro generate
        
        METADATA_PATH=".koro-i18n/translations.jsonl"
        
        if [ -f "$METADATA_PATH" ]; then
          # Count file entries from JSONL
          FILES_COUNT=$(grep -c '"type":"file"' "$METADATA_PATH" || echo "0")
          echo "metadata-path=$METADATA_PATH" >> $GITHUB_OUTPUT
          echo "files-count=$FILES_COUNT" >> $GITHUB_OUTPUT
          echo "✓ Metadata generated with $FILES_COUNT files"
        else
          echo "::error::Failed to generate metadata file"
          exit 1
        fi

    - name: Commit and push metadata
      if: inputs.commit-changes == 'true' && steps.check-config.outputs.config_exists == 'true'
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: |
        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Check if .koro-i18n directory exists and has the generated JSONL manifest
        if [ -f ".koro-i18n/translations.jsonl" ]; then
          git add .koro-i18n/translations.jsonl

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "ℹ No changes to commit - metadata is up to date"
          else
            git commit -m "$COMMIT_MESSAGE"
            git push
            echo "✓ Metadata committed and pushed"
          fi
        else
          echo "::error::No metadata file to commit"
          exit 1
        fi
