# GitHub Actions Workflow Template for Client Repositories
#
# Place this file in your repository at: .github/workflows/i18n-upload.yml
#
# This workflow processes translation files and uploads them to the I18n Platform

name: Upload Translations to I18n Platform

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'locales/**'
      - 'src/locales/**'
      - '.i18n-platform.toml'
  workflow_dispatch:

jobs:
  upload-translations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install I18n Platform Client
        run: npm install -g @i18n-platform/client
      
      - name: Process and upload translations
        env:
          I18N_PLATFORM_URL: ${{ secrets.I18N_PLATFORM_URL || 'https://i18n-platform.workers.dev' }}
          I18N_PLATFORM_API_KEY: ${{ secrets.I18N_PLATFORM_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          i18n-upload
      
      - name: Generate translation logs (optional)
        run: |
          mkdir -p .i18n-logs
          
          # Generate commit history for translations
          git log --all --grep="feat(i18n):" --pretty=format:'{"sha":"%H","author":"%an","email":"%ae","date":"%ai","message":"%s"}' -n 100 > .i18n-logs/commits.jsonl || echo "" > .i18n-logs/commits.jsonl
          
          # Convert to JSON
          node -e "
            const fs = require('fs');
            const lines = fs.readFileSync('.i18n-logs/commits.jsonl', 'utf8').trim().split('\n').filter(l => l);
            const commits = lines.map(l => JSON.parse(l));
            fs.writeFileSync('.i18n-logs/commits.json', JSON.stringify({
              generated_at: new Date().toISOString(),
              repository: '${{ github.repository }}',
              total: commits.length,
              commits: commits
            }, null, 2));
          "
          
          # Generate contributor stats
          git log --all --grep="feat(i18n):" --pretty=format:'%an <%ae>' | sort | uniq -c | sort -rn > .i18n-logs/contributors.txt || echo "" > .i18n-logs/contributors.txt
          
          node -e "
            const fs = require('fs');
            const lines = fs.readFileSync('.i18n-logs/contributors.txt', 'utf8').trim().split('\n').filter(l => l);
            const contributors = lines.map(line => {
              const match = line.trim().match(/^(\d+)\s+(.+)\s+<(.+)>$/);
              if (match) return { name: match[2], email: match[3], commits: parseInt(match[1]) };
              return null;
            }).filter(c => c);
            fs.writeFileSync('.i18n-logs/contributors.json', JSON.stringify({
              generated_at: new Date().toISOString(),
              repository: '${{ github.repository }}',
              total: contributors.length,
              contributors: contributors
            }, null, 2));
          "
      
      - name: Commit logs to repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .i18n-logs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Update translation logs [skip ci]" && git push)
      
      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: i18n-logs
          path: .i18n-logs/
          retention-days: 90
