name: 'Koro i18n Sync'
description: 'Sync translations between your repository and Koro i18n platform'
author: 'Koro i18n'

branding:
  icon: 'refresh-cw'
  color: 'blue'

inputs:
  project-name:
    description: 'Project name on the platform'
    required: true
  platform-url:
    description: 'URL of the Koro i18n platform'
    required: false
    default: 'https://koro.f3liz.workers.dev'
  action:
    description: 'Action to perform: push (sync source keys), pull (download translations), or sync (both)'
    required: false
    default: 'sync'
  config-path:
    description: 'Path to .koro-i18n.repo.config.toml config file'
    required: false
    default: '.koro-i18n.repo.config.toml'
  commit-changes:
    description: 'Whether to commit and push changes'
    required: false
    default: 'true'
  commit-message:
    description: 'Commit message for translation updates'
    required: false
    default: 'chore: sync translations from Koro i18n'

outputs:
  pushed:
    description: 'Whether source keys were pushed'
    value: ${{ steps.preprocess.outputs.files_count }}
  pulled:
    description: 'Number of translations pulled'
    value: ${{ steps.pull.outputs.pulled }}

runs:
  using: 'composite'
  steps:
    # =========================================================================
    # Setup
    # =========================================================================
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false

    - name: Check config exists
      id: check-config
      shell: bash
      run: |
        # Check for TOML config
        if [ -f ".koro-i18n.repo.config.toml" ]; then
          echo "config_exists=true" >> $GITHUB_OUTPUT
          echo "config_file=.koro-i18n.repo.config.toml" >> $GITHUB_OUTPUT
          echo "✓ Found .koro-i18n.repo.config.toml"
        elif [ -f "${{ inputs.config-path }}" ]; then
          echo "config_exists=true" >> $GITHUB_OUTPUT
          echo "config_file=${{ inputs.config-path }}" >> $GITHUB_OUTPUT
          echo "✓ Found ${{ inputs.config-path }}"
        else
          echo "config_exists=false" >> $GITHUB_OUTPUT
          echo "::error::No config found. Create .koro-i18n.repo.config.toml"
          exit 1
        fi

    - name: Get OIDC Token
      id: oidc
      if: steps.check-config.outputs.config_exists == 'true'
      shell: bash
      run: |
        OIDC_TOKEN=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{ inputs.platform-url }}" | jq -r .value)
        if [ -z "$OIDC_TOKEN" ] || [ "$OIDC_TOKEN" = "null" ]; then
          echo "::error::Failed to get OIDC token"
          exit 1
        fi
        echo "token=$OIDC_TOKEN" >> $GITHUB_OUTPUT
        echo "✓ OIDC token obtained"

    # =========================================================================
    # Push: Sync source keys to platform
    # =========================================================================
    - name: Install koro-i18n client
      id: install-client
      if: (inputs.action == 'push' || inputs.action == 'sync') && steps.check-config.outputs.config_exists == 'true'
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        # Navigate from action path to client-library
        CLIENT_LIB_PATH="$ACTION_PATH/../../../client-library"
        
        if [ ! -d "$CLIENT_LIB_PATH" ]; then
          echo "::error::Client library not found at $CLIENT_LIB_PATH"
          exit 1
        fi
        
        cd "$CLIENT_LIB_PATH"
        gem build koro_i18n.gemspec
        gem install ./koro_i18n-*.gem
        
        echo "cli-command=koro" >> $GITHUB_OUTPUT
        echo "✓ koro-i18n client installed"

    - name: Push source keys
      id: preprocess
      if: (inputs.action == 'push' || inputs.action == 'sync') && steps.check-config.outputs.config_exists == 'true'
      shell: bash
      env:
        CONFIG_PATH: ${{ steps.check-config.outputs.config_file }}
        KORO_TOKEN: ${{ steps.oidc.outputs.token }}
        PLATFORM_URL: ${{ inputs.platform-url }}
        PROJECT_NAME: ${{ inputs.project-name }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        echo ""
        echo "🚀 Pushing source keys to platform..."
        
        # Set environment variables for the Ruby client
        export KORO_API_URL="$PLATFORM_URL"
        export KORO_TOKEN="$KORO_TOKEN"
        
        # Run koro push command
        if koro push 2>&1; then
          echo "files_count=1" >> $GITHUB_OUTPUT
          echo "✓ Source keys pushed successfully"
        else
          echo "::error::Failed to push source keys"
          exit 1
        fi



    # =========================================================================
    # Pull: Download approved translations
    # =========================================================================
    - name: Pull translations
      id: pull
      if: (inputs.action == 'pull' || inputs.action == 'sync') && steps.check-config.outputs.config_exists == 'true'
      shell: bash
      env:
        PLATFORM_URL: ${{ inputs.platform-url }}
        KORO_TOKEN: ${{ steps.oidc.outputs.token }}
        PROJECT_NAME: ${{ inputs.project-name }}
      run: |
        echo ""
        echo "📥 Pulling approved translations..."
        
        # Set environment variables for the Ruby client
        export KORO_API_URL="$PLATFORM_URL"
        export KORO_TOKEN="$KORO_TOKEN"
        
        # Run koro pull command
        if OUTPUT=$(koro pull 2>&1); then
          echo "$OUTPUT"
          
          # Extract number of pulled translations from output
          PULLED=$(echo "$OUTPUT" | grep -oP 'Pulled \K\d+' || echo "0")
          echo "pulled=$PULLED" >> $GITHUB_OUTPUT
          echo "✓ Pulled $PULLED translation(s)"
        else
          echo "::error::Failed to pull translations"
          exit 1
        fi

    - name: Commit translations
      if: (inputs.action == 'pull' || inputs.action == 'sync') && inputs.commit-changes == 'true' && steps.pull.outputs.pulled != '0'
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Stage translation files
        git add -A

        if git diff --staged --quiet; then
          echo "ℹ No translation changes to commit"
          exit 0
        fi

        git commit -m "$COMMIT_MESSAGE"
        git push
        echo "✓ Translation changes committed and pushed"

    # =========================================================================
    # Summary
    # =========================================================================
    - name: Summary
      if: always() && steps.check-config.outputs.config_exists == 'true'
      shell: bash
      env:
        PUSHED: ${{ steps.preprocess.outputs.files_count || '0' }}
        PULLED: ${{ steps.pull.outputs.pulled || '0' }}
      run: |
        echo ""
        echo "📊 Sync Summary"
        echo "  Pushed: $PUSHED"
        echo "  Pulled: $PULLED translations"
